# Site settings
title: ole.bertr.am
description: "Ole Bertram's website and portfolio."
baseurl: ""
url: "https://ole.bertr.am"

# External links
email: mailto:ole@bertr.am
twitter: https://twitter.com/elomatreb
github: https://github.com/elomatreb
codepen: http://codepen.io/elomatreb

# Build settings
markdown: redcarpet
permalink: :categories/:title.html
include:
  - .htaccess
exclude:
  - Gemfile
  - Rakefile
  - elomatreb.eu.sublime-project
  - elomatreb.eu.sublime-workspace
  - vendor
  - README.md
  - LICENSE.md

gems:
  - jekyll-sitemap

redcarpet:
  extensions:
    - smart
    - fenced_code_blocks
    - no_intra_emphasis
    - with_toc_data

sass:
  sass_dir: css
  style: :compressed

image:
  source: "img"
  output: "img/generated"
  presets:
    default:
      width: 760
      height: AUTO
