# Site settings
title: elomatreb
email: ole@elomatreb.eu
description: "elomatreb's website and portfolio."
baseurl: ""
url: "https://elomatreb.eu"

# Build settings
markdown: redcarpet
permalink: :categories/:title.html
include:
  - .htaccess
exclude:
  - Gemfile
  - vendor

redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - with_toc_data

sass:
  sass_dir: css
  style: :compressed
