# Site settings
title: elomatreb.eu
email: ole@elomatreb.eu
description: "elomatreb's blog about web design and development."
baseurl: ""
url: "https://elomatreb.eu"

# Build settings
markdown: kramdown
permalink: :title.html
include:
  - .htaccess
