# Site settings
title: elomatreb
email: ole@elomatreb.eu
description: "elomatreb's website and portfolio."
baseurl: ""
url: "https://elomatreb.eu"

# Build settings
markdown: kramdown
permalink: :title.html
include:
  - .htaccess
