# Site settings
title: elomatreb
email: ole@elomatreb.eu
description: "elomatreb's website and portfolio."
baseurl: ""
url: "https://elomatreb.eu"

# Build settings
markdown: kramdown
permalink: :categories/:title.html
include:
  - .htaccess

sass:
  sass_dir: css
  style: :compressed
